In [2]:
import numpy as np
import os
import glob
import torch
from data_loaders.dataloader3d import get_dataloader, load_data, MotionDataset, TestDataset, compute_dct_stats
import pandas as pd

In [12]:
dffid=pd.read_csv('metrics/crossval_summary_fid_dcttransformer.csv')
dfaction=pd.read_csv('metrics/crossval_summary_metrics_per_action_dcttransformer.csv')
dfmetric=pd.read_csv('metrics/crossval_summary_metrics_dcttransformer.csv')

In [14]:
dffid.head()

,model,keypointtype,window,use_dct,checkpoint,FID,real_windows,gen_windows
0,config1,openpose,30,True,latest,0.131587,1600,1600
1,config1,openpose,30,True,best,0.138525,1600,1600
2,config2,openpose,30,True,latest,0.102601,1600,1600
3,config2,openpose,30,True,best,0.134714,1600,1600
4,config3,openpose,60,True,latest,0.245380,815,815

In [15]:
dfmetric.head()

,model,keypointtype,window,use_dct,checkpoint,metric_type,MPJPE_mean,MPJPE_std,PAMPJPE_mean,PAMPJPE_std,...,jitter_mean,jitter_std,MPJRE_mean,MPJRE_std,dtw_distance_transl_mean,dtw_distance_transl_std,MPJPE_6d_mean,MPJPE_6d_std,PAMPJPE_6d_mean,PAMPJPE_6d_std
0,config1,openpose,30,True,latest,per_window,0.144416,0.054968,0.056098,0.019109,...,301.475916,68.206276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,config1,openpose,30,True,latest,full_concat,0.227133,0.092746,0.061087,0.017023,...,304.743028,59.226065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,config1,openpose,30,True,best,per_window,0.154772,0.060820,0.059847,0.019937,...,340.847041,97.250727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,config1,openpose,30,True,best,full_concat,0.238560,0.124312,0.063296,0.017325,...,337.751180,82.336807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,config2,openpose,30,True,latest,per_window,0.151095,0.054404,0.058980,0.019348,...,317.084854,68.006467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
t=dfaction[dfaction['model']=='config1']
t

0       True
1       True
2       True
3       True
4       True
       ...
139    False
140    False
141    False
142    False
143    False
Name: model, Length: 144, dtype: bool

In [7]:
np.load('results/crossval_metrics_best.npy', allow_pickle=True)

array([{'sample_id': 0, 'action': 'a1', 'MPJPE': 0.10110200258483647, 'PAMPJPE': 0.04448290193760133, 'dtw_distance_trajectory': 0.053092121176592885, 'jitter': 376.39259338378906},
       {'sample_id': 1, 'action': 'a1', 'MPJPE': 0.10393423104650212, 'PAMPJPE': 0.03851738759916028, 'dtw_distance_trajectory': 0.053523519373356775, 'jitter': 285.7638282775879},
       {'sample_id': 2, 'action': 'a1', 'MPJPE': 0.09849362180957243, 'PAMPJPE': 0.04879913116149336, 'dtw_distance_trajectory': 0.04345949277270138, 'jitter': 398.22982025146484},
       {'sample_id': 3, 'action': 'a1', 'MPJPE': 0.10186057232390353, 'PAMPJPE': 0.04360908685750979, 'dtw_distance_trajectory': 0.0551996163076971, 'jitter': 294.75667572021484},
       {'sample_id': 4, 'action': 'a2', 'MPJPE': 0.18750345023044557, 'PAMPJPE': 0.05732196263232343, 'dtw_distance_trajectory': 0.08801676268179917, 'jitter': 489.87916564941406},
       {'sample_id': 5, 'action': 'a2', 'MPJPE': 0.16515862336291648, 'PAMPJPE': 0.05241129142843931, 'dtw_distance_trajectory': 0.06765411594479202, 'jitter': 373.2692413330078},
       {'sample_id': 6, 'action': 'a2', 'MPJPE': 0.181004812490379, 'PAMPJPE': 0.057661158839806576, 'dtw_distance_trajectory': 0.07508747254502615, 'jitter': 512.9531402587891},
       {'sample_id': 7, 'action': 'a2', 'MPJPE': 0.15121224469790762, 'PAMPJPE': 0.05860096353522762, 'dtw_distance_trajectory': 0.05138455207400334, 'jitter': 510.6269989013672},
       {'sample_id': 8, 'action': 'a3', 'MPJPE': 0.22616840113574999, 'PAMPJPE': 0.09600907073371791, 'dtw_distance_trajectory': 0.08845680900519207, 'jitter': 294.1532325744629},
       {'sample_id': 9, 'action': 'a3', 'MPJPE': 0.22428487412726425, 'PAMPJPE': 0.0971957511324484, 'dtw_distance_trajectory': 0.09383940498594613, 'jitter': 267.98604075113934},
       {'sample_id': 10, 'action': 'a3', 'MPJPE': 0.13243807379581782, 'PAMPJPE': 0.07025085195648949, 'dtw_distance_trajectory': 0.061954128578231446, 'jitter': 340.6107635498047},
       {'sample_id': 11, 'action': 'a3', 'MPJPE': 0.30720572215465763, 'PAMPJPE': 0.09475783039070507, 'dtw_distance_trajectory': 0.19058694172838242, 'jitter': 236.11806106567383},
       {'sample_id': 12, 'action': 'a3', 'MPJPE': 0.1828694268276759, 'PAMPJPE': 0.09072333604001757, 'dtw_distance_trajectory': 0.10951145216340318, 'jitter': 254.9018096923828},
       {'sample_id': 13, 'action': 'a4', 'MPJPE': 0.1138734323149707, 'PAMPJPE': 0.05217026710226295, 'dtw_distance_trajectory': 0.043309982454476155, 'jitter': 411.2528889973958},
       {'sample_id': 14, 'action': 'a4', 'MPJPE': 0.1322639441808546, 'PAMPJPE': 0.0745237982321139, 'dtw_distance_trajectory': 0.04134986800887102, 'jitter': 370.7975260416667},
       {'sample_id': 15, 'action': 'a4', 'MPJPE': 0.10690191732516811, 'PAMPJPE': 0.06190434452081662, 'dtw_distance_trajectory': 0.033378751569128076, 'jitter': 395.68182373046875},
       {'sample_id': 16, 'action': 'a4', 'MPJPE': 0.11948932130625262, 'PAMPJPE': 0.07773730895203883, 'dtw_distance_trajectory': 0.03537544211794704, 'jitter': 384.0992126464844},
       {'sample_id': 17, 'action': 'a5', 'MPJPE': 0.2506198103574238, 'PAMPJPE': 0.12155869330272528, 'dtw_distance_trajectory': 0.1270987986740712, 'jitter': 347.99059295654297},
       {'sample_id': 18, 'action': 'a5', 'MPJPE': 0.2637623963036726, 'PAMPJPE': 0.11832362158741327, 'dtw_distance_trajectory': 0.15919805949693547, 'jitter': 368.689697265625},
       {'sample_id': 19, 'action': 'a5', 'MPJPE': 0.20996913148436144, 'PAMPJPE': 0.12116213024846756, 'dtw_distance_trajectory': 0.1225645373973212, 'jitter': 307.6050491333008},
       {'sample_id': 20, 'action': 'a5', 'MPJPE': 0.2388882263902394, 'PAMPJPE': 0.12383130560852718, 'dtw_distance_trajectory': 0.14558189975058136, 'jitter': 414.3370768229167},
       {'sample_id': 21, 'action': 'a1', 'MPJPE': 0.10550627551895163, 'PAMPJPE': 0.034248019083832786, 'dtw_distance_trajectory': 0.054336989482571485, 'jitter': 354.6279296875},
       {'sample_id': 22, 'action': 'a1', 'MPJPE': 0.10035568633647812, 'PAMPJPE': 0.02977679313210464, 'dtw_distance_trajectory': 0.06257998446387329, 'jitter': 385.3892313639323},
       {'sample_id': 23, 'action': 'a1', 'MPJPE': 0.14642169387042572, 'PAMPJPE': 0.03898274630612768, 'dtw_distance_trajectory': 0.0932702188558095, 'jitter': 452.12084197998047},
       {'sample_id': 24, 'action': 'a1', 'MPJPE': 0.10044615451022533, 'PAMPJPE': 0.030516768397504102, 'dtw_distance_trajectory': 0.06000350567302653, 'jitter': 306.4602966308594},
       {'sample_id': 25, 'action': 'a1', 'MPJPE': 0.13710740477681324, 'PAMPJPE': 0.030385695110520684, 'dtw_distance_trajectory': 0.08275617078581222, 'jitter': 463.48753865559894},
       {'sample_id': 26, 'action': 'a1', 'MPJPE': 0.17130362346345862, 'PAMPJPE': 0.0408960612472841, 'dtw_distance_trajectory': 0.10455535260931428, 'jitter': 475.99678802490234},
       {'sample_id': 27, 'action': 'a1', 'MPJPE': 0.06437173903030002, 'PAMPJPE': 0.030992804123991274, 'dtw_distance_trajectory': 0.03998923754887618, 'jitter': 357.6736094156901},
       {'sample_id': 28, 'action': 'a1', 'MPJPE': 0.08220167932283744, 'PAMPJPE': 0.02658311035582309, 'dtw_distance_trajectory': 0.048812580680228486, 'jitter': 351.0066324869792},
       {'sample_id': 29, 'action': 'a1', 'MPJPE': 0.09015561754800411, 'PAMPJPE': 0.03531044562980176, 'dtw_distance_trajectory': 0.0387400479043101, 'jitter': 369.2430229187012},
       {'sample_id': 30, 'action': 'a2', 'MPJPE': 0.09131872399372394, 'PAMPJPE': 0.03194090434165804, 'dtw_distance_trajectory': 0.0425760522196332, 'jitter': 545.1387023925781},
       {'sample_id': 31, 'action': 'a2', 'MPJPE': 0.09854504221966319, 'PAMPJPE': 0.034826696581291734, 'dtw_distance_trajectory': 0.03973791541502945, 'jitter': 443.2824401855469},
       {'sample_id': 32, 'action': 'a2', 'MPJPE': 0.11623515959709387, 'PAMPJPE': 0.03532091329574142, 'dtw_distance_trajectory': 0.06811886424566327, 'jitter': 514.1849975585938},
       {'sample_id': 33, 'action': 'a2', 'MPJPE': 0.10512060341260372, 'PAMPJPE': 0.03684400666001685, 'dtw_distance_trajectory': 0.055736550109050105, 'jitter': 423.4289042154948},
       {'sample_id': 34, 'action': 'a3', 'MPJPE': 0.16561456627266577, 'PAMPJPE': 0.05596350785292458, 'dtw_distance_trajectory': 0.11165457233952852, 'jitter': 281.7673060099284},
       {'sample_id': 35, 'action': 'a3', 'MPJPE': 0.21021000890783326, 'PAMPJPE': 0.06066188227301338, 'dtw_distance_trajectory': 0.12450746569699513, 'jitter': 302.00193786621094},
       {'sample_id': 36, 'action': 'a3', 'MPJPE': 0.18253423506422764, 'PAMPJPE': 0.06251687491135037, 'dtw_distance_trajectory': 0.11011379052177905, 'jitter': 289.32171630859375},
       {'sample_id': 37, 'action': 'a3', 'MPJPE': 0.13474759256083424, 'PAMPJPE': 0.04736267906240584, 'dtw_distance_trajectory': 0.08141984486629895, 'jitter': 325.4429168701172},
       {'sample_id': 38, 'action': 'a4', 'MPJPE': 0.07339118037042165, 'PAMPJPE': 0.03764784685771924, 'dtw_distance_trajectory': 0.03576323139588917, 'jitter': 326.6503601074219},
       {'sample_id': 39, 'action': 'a4', 'MPJPE': 0.05993485489252816, 'PAMPJPE': 0.03425654176701262, 'dtw_distance_trajectory': 0.028605034290545877, 'jitter': 361.97218322753906},
       {'sample_id': 40, 'action': 'a4', 'MPJPE': 0.07065866391119457, 'PAMPJPE': 0.036319278793894794, 'dtw_distance_trajectory': 0.034095074798202035, 'jitter': 336.26441192626953},
       {'sample_id': 41, 'action': 'a4', 'MPJPE': 0.06609803658610984, 'PAMPJPE': 0.03458428029491829, 'dtw_distance_trajectory': 0.037042970268426706, 'jitter': 314.687931060791},
       {'sample_id': 42, 'action': 'a5', 'MPJPE': 0.18729316028895296, 'PAMPJPE': 0.07511810916016384, 'dtw_distance_trajectory': 0.1138647509213581, 'jitter': 219.27037484305245},
       {'sample_id': 43, 'action': 'a5', 'MPJPE': 0.18229489995869885, 'PAMPJPE': 0.0601985285303397, 'dtw_distance_trajectory': 0.10206440903244081, 'jitter': 233.13854435512},
       {'sample_id': 44, 'action': 'a5', 'MPJPE': 0.1893811246843991, 'PAMPJPE': 0.08030686757903925, 'dtw_distance_trajectory': 0.08845793688962399, 'jitter': 205.52999550955636},
       {'sample_id': 45, 'action': 'a5', 'MPJPE': 0.1727828742880228, 'PAMPJPE': 0.06499223653110377, 'dtw_distance_trajectory': 0.07246507328887568, 'jitter': 236.87437983921595},
       {'sample_id': 46, 'action': 'a1', 'MPJPE': 0.10662313145747326, 'PAMPJPE': 0.056167893460202976, 'dtw_distance_trajectory': 0.05525465928118815, 'jitter': 383.8564961751302},
       {'sample_id': 47, 'action': 'a1', 'MPJPE': 0.15566518692583772, 'PAMPJPE': 0.06288319465520882, 'dtw_distance_trajectory': 0.08297015026437356, 'jitter': 412.2040201822917},
       {'sample_id': 48, 'action': 'a1', 'MPJPE': 0.0860255428442266, 'PAMPJPE': 0.049259869721338535, 'dtw_distance_trajectory': 0.040759008101940976, 'jitter': 416.82521565755206},
       {'sample_id': 49, 'action': 'a1', 'MPJPE': 0.11263882094593963, 'PAMPJPE': 0.05172034158109656, 'dtw_distance_trajectory': 0.05461670027525086, 'jitter': 395.2501525878906},
       {'sample_id': 50, 'action': 'a2', 'MPJPE': 0.10328721663833944, 'PAMPJPE': 0.05792562297807829, 'dtw_distance_trajectory': 0.04510138508906023, 'jitter': 408.16663614908856},
       {'sample_id': 51, 'action': 'a2', 'MPJPE': 0.09034367326258394, 'PAMPJPE': 0.060174453463577096, 'dtw_distance_trajectory': 0.03637145737245143, 'jitter': 322.0866394042969},
       {'sample_id': 52, 'action': 'a2', 'MPJPE': 0.08379369422705828, 'PAMPJPE': 0.05702503935669682, 'dtw_distance_trajectory': 0.03946765946075461, 'jitter': 351.8749593098958},
       {'sample_id': 53, 'action': 'a2', 'MPJPE': 0.10788837728537591, 'PAMPJPE': 0.05683846924936567, 'dtw_distance_trajectory': 0.06768652754414517, 'jitter': 370.58917236328125},
       {'sample_id': 54, 'action': 'a3', 'MPJPE': 0.19691740395599786, 'PAMPJPE': 0.06806401948003946, 'dtw_distance_trajectory': 0.13075872961657484, 'jitter': 258.77224513462613},
       {'sample_id': 55, 'action': 'a3', 'MPJPE': 0.13849910349967987, 'PAMPJPE': 0.06290631285957804, 'dtw_distance_trajectory': 0.0930002980370023, 'jitter': 258.2027151925223},
       {'sample_id': 56, 'action': 'a3', 'MPJPE': 0.13733433293775985, 'PAMPJPE': 0.06598563484283496, 'dtw_distance_trajectory': 0.07358588180388069, 'jitter': 299.8958206176758},
       {'sample_id': 57, 'action': 'a3', 'MPJPE': 0.18628313286754694, 'PAMPJPE': 0.07194584351929646, 'dtw_distance_trajectory': 0.1107239942581855, 'jitter': 260.2725045340402},
       {'sample_id': 58, 'action': 'a3', 'MPJPE': 0.12126717447362777, 'PAMPJPE': 0.0650197608392066, 'dtw_distance_trajectory': 0.06328083606083876, 'jitter': 283.5169372558594},
       {'sample_id': 59, 'action': 'a4', 'MPJPE': 0.10453027645184687, 'PAMPJPE': 0.05026966359256286, 'dtw_distance_trajectory': 0.0443629471665799, 'jitter': 274.02605692545575},
       {'sample_id': 60, 'action': 'a4', 'MPJPE': 0.07845963615185214, 'PAMPJPE': 0.04454595410117532, 'dtw_distance_trajectory': 0.022722246647182632, 'jitter': 355.5442810058594},
       {'sample_id': 61, 'action': 'a4', 'MPJPE': 0.11261036043564428, 'PAMPJPE': 0.04702822735427805, 'dtw_distance_trajectory': 0.05428791805958472, 'jitter': 262.58349609375},
       {'sample_id': 62, 'action': 'a4', 'MPJPE': 0.0707697018176572, 'PAMPJPE': 0.041771241079586734, 'dtw_distance_trajectory': 0.03291924882806036, 'jitter': 309.09128824869794},
       {'sample_id': 63, 'action': 'a5', 'MPJPE': 0.19465574283352247, 'PAMPJPE': 0.09277939164427725, 'dtw_distance_trajectory': 0.07984127079217321, 'jitter': 248.66719818115234},
       {'sample_id': 64, 'action': 'a5', 'MPJPE': 0.20216176110696815, 'PAMPJPE': 0.09344603829215721, 'dtw_distance_trajectory': 0.09809713454473697, 'jitter': 254.53671264648438},
       {'sample_id': 65, 'action': 'a5', 'MPJPE': 0.20825677015403687, 'PAMPJPE': 0.09477268851274095, 'dtw_distance_trajectory': 0.09293269685645683, 'jitter': 276.2094370524089},
       {'sample_id': 66, 'action': 'a5', 'MPJPE': 0.19472107650895412, 'PAMPJPE': 0.09523797546128537, 'dtw_distance_trajectory': 0.09488088149754659, 'jitter': 285.4587799072266},
       {'sample_id': 0, 'action': 'a1', 'MPJPE': 0.12934998005923454, 'PAMPJPE': 0.04720838958286552, 'dtw_distance_trajectory': 0.07274446563684384, 'jitter': 267.1853892008464},
       {'sample_id': 1, 'action': 'a1', 'MPJPE': 0.0976026097790665, 'PAMPJPE': 0.04480175942583586, 'dtw_distance_trajectory': 0.03308160167997529, 'jitter': 304.1373596191406},
       {'sample_id': 2, 'action': 'a1', 'MPJPE': 0.16743452328366795, 'PAMPJPE': 0.04556091831715627, 'dtw_distance_trajectory': 0.1057867089821521, 'jitter': 294.82252502441406},
       {'sample_id': 3, 'action': 'a1', 'MPJPE': 0.14345863047972618, 'PAMPJPE': 0.04929099826803008, 'dtw_distance_trajectory': 0.06859278375656812, 'jitter': 322.6304117838542},
       {'sample_id': 4, 'action': 'a2', 'MPJPE': 0.1574306654088163, 'PAMPJPE': 0.06139742341024731, 'dtw_distance_trajectory': 0.08399965801867645, 'jitter': 317.7672119140625},
       {'sample_id': 5, 'action': 'a2', 'MPJPE': 0.25226956174125365, 'PAMPJPE': 0.06203923997239493, 'dtw_distance_trajectory': 0.16554857313615182, 'jitter': 226.41893513997397},
       {'sample_id': 6, 'action': 'a2', 'MPJPE': 0.1511441694427716, 'PAMPJPE': 0.04884191449548815, 'dtw_distance_trajectory': 0.07951484769938923, 'jitter': 272.3985595703125},
       {'sample_id': 7, 'action': 'a2', 'MPJPE': 0.19412408252153487, 'PAMPJPE': 0.04787957633967707, 'dtw_distance_trajectory': 0.11184098104485411, 'jitter': 253.08685302734375},
       {'sample_id': 8, 'action': 'a3', 'MPJPE': 0.32446368898065314, 'PAMPJPE': 0.08054937591206954, 'dtw_distance_trajectory': 0.264066265927995, 'jitter': 200.55752754211426},
       {'sample_id': 9, 'action': 'a3', 'MPJPE': 0.18553260103278527, 'PAMPJPE': 0.07508514286693749, 'dtw_distance_trajectory': 0.1192667483651009, 'jitter': 244.42677307128906},
       {'sample_id': 10, 'action': 'a3', 'MPJPE': 0.18689329980446778, 'PAMPJPE': 0.062046793666531264, 'dtw_distance_trajectory': 0.1253621289160127, 'jitter': 222.13410186767578},
       {'sample_id': 11, 'action': 'a3', 'MPJPE': 0.2557089006409463, 'PAMPJPE': 0.06867293244055284, 'dtw_distance_trajectory': 0.21226522125220507, 'jitter': 219.11885356903076},
       {'sample_id': 12, 'action': 'a3', 'MPJPE': 0.19694670784281448, 'PAMPJPE': 0.08695242784081784, 'dtw_distance_trajectory': 0.09476462324651615, 'jitter': 250.15117797851562},
       {'sample_id': 13, 'action': 'a4', 'MPJPE': 0.0911083997264508, 'PAMPJPE': 0.0497581985022141, 'dtw_distance_trajectory': 0.037509190885326456, 'jitter': 336.8486022949219},
       {'sample_id': 14, 'action': 'a4', 'MPJPE': 0.07477911881076428, 'PAMPJPE': 0.04475889620421941, 'dtw_distance_trajectory': 0.02876034630356448, 'jitter': 282.4618784586589},
       {'sample_id': 15, 'action': 'a4', 'MPJPE': 0.09138950544355533, 'PAMPJPE': 0.046693705669718734, 'dtw_distance_trajectory': 0.03713243677581932, 'jitter': 309.4630940755208},
       {'sample_id': 16, 'action': 'a4', 'MPJPE': 0.06607769386801231, 'PAMPJPE': 0.04082604046950635, 'dtw_distance_trajectory': 0.0379557971908367, 'jitter': 297.83069864908856},
       {'sample_id': 17, 'action': 'a5', 'MPJPE': 0.29958767626747496, 'PAMPJPE': 0.0929791924160478, 'dtw_distance_trajectory': 0.21242291118900636, 'jitter': 229.99994659423828},
       {'sample_id': 18, 'action': 'a5', 'MPJPE': 0.30345379793413524, 'PAMPJPE': 0.0932016236000327, 'dtw_distance_trajectory': 0.22267078590040298, 'jitter': 196.72473362513952},
       {'sample_id': 19, 'action': 'a5', 'MPJPE': 0.21832964186537937, 'PAMPJPE': 0.08907299463210287, 'dtw_distance_trajectory': 0.12256031939469357, 'jitter': 206.10711542765299},
       {'sample_id': 20, 'action': 'a5', 'MPJPE': 0.2891043710978716, 'PAMPJPE': 0.07942600458006703, 'dtw_distance_trajectory': 0.15570239311067255, 'jitter': 189.18919154575892},
       {'sample_id': 21, 'action': 'a1', 'MPJPE': 0.11598627450299887, 'PAMPJPE': 0.03680586249559541, 'dtw_distance_trajectory': 0.0846553030875039, 'jitter': 290.4501266479492},
       {'sample_id': 22, 'action': 'a1', 'MPJPE': 0.10001759033160329, 'PAMPJPE': 0.03170073892295578, 'dtw_distance_trajectory': 0.06273397049794442, 'jitter': 213.78729756673178},
       {'sample_id': 23, 'action': 'a1', 'MPJPE': 0.07475365020327324, 'PAMPJPE': 0.03304319313256928, 'dtw_distance_trajectory': 0.03871026266508863, 'jitter': 283.7241668701172},
       {'sample_id': 24, 'action': 'a1', 'MPJPE': 0.09727103887659742, 'PAMPJPE': 0.03392104420180079, 'dtw_distance_trajectory': 0.047083735512519855, 'jitter': 255.7538859049479},
       {'sample_id': 25, 'action': 'a2', 'MPJPE': 0.09954640845383272, 'PAMPJPE': 0.04566806256987725, 'dtw_distance_trajectory': 0.053189167641086776, 'jitter': 305.5009307861328},
       {'sample_id': 26, 'action': 'a2', 'MPJPE': 0.10123290992125651, 'PAMPJPE': 0.041883537226114285, 'dtw_distance_trajectory': 0.05638520980964098, 'jitter': 264.88170369466144},
       {'sample_id': 27, 'action': 'a2', 'MPJPE': 0.12254543553185582, 'PAMPJPE': 0.03660298314708325, 'dtw_distance_trajectory': 0.09351106820107614, 'jitter': 288.545654296875},
       {'sample_id': 28, 'action': 'a2', 'MPJPE': 0.15334543117733, 'PAMPJPE': 0.03710972869793697, 'dtw_distance_trajectory': 0.11672564162238425, 'jitter': 257.69446818033856},
       {'sample_id': 29, 'action': 'a3', 'MPJPE': 0.23299926119756245, 'PAMPJPE': 0.052746035744913156, 'dtw_distance_trajectory': 0.19279116479463596, 'jitter': 226.60641818576389},
       {'sample_id': 30, 'action': 'a3', 'MPJPE': 0.18439117521049792, 'PAMPJPE': 0.05113288586093588, 'dtw_distance_trajectory': 0.1294310069379346, 'jitter': 226.3405303955078},
       {'sample_id': 31, 'action': 'a3', 'MPJPE': 0.21069633054997697, 'PAMPJPE': 0.06813496649118823, 'dtw_distance_trajectory': 0.15978789432845827, 'jitter': 235.7053426106771},
       {'sample_id': 32, 'action': 'a3', 'MPJPE': 0.19419013279893016, 'PAMPJPE': 0.05489666749711295, 'dtw_distance_trajectory': 0.149803204327093, 'jitter': 206.71578301323785},
       {'sample_id': 33, 'action': 'a3', 'MPJPE': 0.18187138997263178, 'PAMPJPE': 0.0546485268570612, 'dtw_distance_trajectory': 0.1200726563376873, 'jitter': 242.9383773803711},
       {'sample_id': 34, 'action': 'a4', 'MPJPE': 0.16194621414195562, 'PAMPJPE': 0.04772264491939796, 'dtw_distance_trajectory': 0.09985680329616975, 'jitter': 295.1161600748698},
       {'sample_id': 35, 'action': 'a4', 'MPJPE': 0.11691786186761897, 'PAMPJPE': 0.03967235503478067, 'dtw_distance_trajectory': 0.059947977682666374, 'jitter': 327.9698486328125},
       {'sample_id': 36, 'action': 'a4', 'MPJPE': 0.12506052179512964, 'PAMPJPE': 0.04388721995895111, 'dtw_distance_trajectory': 0.0627109997910759, 'jitter': 318.8013203938802},
       {'sample_id': 37, 'action': 'a4', 'MPJPE': 0.09577009305253543, 'PAMPJPE': 0.035234884491249646, 'dtw_distance_trajectory': 0.05154756727005192, 'jitter': 334.0515543619792},
       {'sample_id': 38, 'action': 'a5', 'MPJPE': 0.18158994222672153, 'PAMPJPE': 0.061191648222813894, 'dtw_distance_trajectory': 0.1040246968211951, 'jitter': 201.3338156806098},
       {'sample_id': 39, 'action': 'a5', 'MPJPE': 0.20533637921429554, 'PAMPJPE': 0.06935777468198284, 'dtw_distance_trajectory': 0.12081551775106893, 'jitter': 190.57634989420572},
       {'sample_id': 40, 'action': 'a5', 'MPJPE': 0.16941925441609615, 'PAMPJPE': 0.05910648543823328, 'dtw_distance_trajectory': 0.10217832373902655, 'jitter': 185.71781073676215},
       {'sample_id': 41, 'action': 'a5', 'MPJPE': 0.17210548493245278, 'PAMPJPE': 0.06514460342143603, 'dtw_distance_trajectory': 0.10615528187674189, 'jitter': 187.36242251925998},
       {'sample_id': 42, 'action': 'a1', 'MPJPE': 0.06999569354394157, 'PAMPJPE': 0.03707610424884866, 'dtw_distance_trajectory': 0.029850401491509325, 'jitter': 273.30462951660155},

In [12]:
df = pd.read_csv('C:\\Users\\Rui\\Vorlesungskript\\Master\\Thesis\\Thesis_project\\2024-02470_Subject_CRF_v2.csv')

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io

In [ ]:
# Calculate Age (Assuming current year is 2024 for the baseline)
current_year = 2026
df['Age'] = current_year - df['Birthyear (yyyy)']
df['Gender'] = df['Sex (m / f)'].map({'m': 'Male', 'f': 'Female'})

# Set the visual style for the plots
sns.set_theme(style="whitegrid")

# --- PLOT 2: Age Distribution by Sex (Stacked Histogram) ---
plt.figure(figsize=(8, 6))

# 'hue' splits the bars by Sex
# 'multiple="stack"' puts them on top of each other for total count visibility
sns.histplot(
    data=df, 
    x='Age', 
    hue='Gender', 
    multiple="stack", 
    bins=8, 
    palette='pastel',
    edgecolor=".3" # Adds a slight border to the bars for better visibility
)

plt.title('Participant Age Distribution by Sex')
plt.xlabel('Age (Years)')
plt.ylabel('Number of Participants')

# This ensures the legend title is clean
plt.legend(title='Gender', labels=['Female', 'Male'])

plt.savefig('age_distribution_by_sex.png', dpi=300)
plt.close()

# --- PLOT 3: Height vs Weight Scatter ---
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='Height (cm)', y='Weight (kg)', hue='Gender', s=100)
plt.title('Height/Weight correlation')
plt.savefig('height_weight_scatter.png', dpi=300)
plt.close()

print("All plots have been saved to your current folder.")

All plots have been saved to your current folder.

In [ ]:
data=np.load("mydataset/gait_354\\20251222_c1_a1_Take1\\split_subjects\\0\\fit-smplx\\smpl-keypoints-3d_cut.npy")

In [ ]:
data.shape

(76, 22, 3)

In [ ]:
def root_normalize_and_trajectory(data):
    assert len(data.shape)==3  # (frames, joints, 3)
    if data.shape[1]==23:
        root = (data[:,7]+data[:, 10])/2
        data=(data - root[:,np.newaxis, :])
        trajectory=root
        trajectory=root - root[0:1]  
        return data.reshape(data.shape[0], -1), trajectory.reshape(data.shape[0], -1)
    elif data.shape[1]==22:
        root=data[:,0,:].copy()
        data=(data - root[:,np.newaxis, :]) 
        return data
    else:
        raise ValueError(f"Unknown keypoint type")

In [ ]:
test=root_normalize_and_trajectory(data)

In [2]:
#a,b = load_data("final_dataset", split='train', keypointtype='openpose')
a,b,c = load_data("final_dataset", split='test', keypointtype='openpose')

In [3]:
dataset = TestDataset(
    "gait",
    a,
    b,
    betas=c,
    input_motion_length=60,
)

In [ ]:
dataset = MotionDataset(
    "gait",
    a,
    b,
    input_motion_length=30,
)

In [ ]:
dataset = MotionDataset(
    "gait",
    a,
    b,
    input_motion_length=60,
    use_dct=True,
)

In [4]:
len(dataset)

312

In [ ]:
mean, std=compute_dct_stats(dataset)

In [ ]:
print("mean max:", mean.max(), "mean min:", mean.min(), "mean mean:", mean.mean())
print("std max:", std.max(), "std min:", std.min(), "std mean:", std.mean())

mean max: tensor(4.1271) mean min: tensor(-6.3546) mean mean: tensor(-0.0185)
std max: tensor(4.0143) std min: tensor(0.0100) std mean: tensor(0.0846)

In [5]:
dataloader = get_dataloader(
    dataset, "test", batch_size=1, num_workers=1
)

In [6]:
print(len(dataset))        # number of samples
print(type(dataset))

312
<class 'data_loaders.dataloader3d.TestDataset'>

In [8]:
i=0
for batch in dataloader:
    images, labels,betas,d,e = batch
    print(d)  # shapes of the batch
    print(e)
    i+=1
    if i==10:
        break

('a1',)
('gait_011_a100',)
('a1',)
('gait_011_a110',)
('a1',)
('gait_011_a101',)
('a1',)
('gait_011_a111',)
('a2',)
('gait_011_a200',)
('a2',)
('gait_011_a210',)
('a2',)
('gait_011_a201',)
('a2',)
('gait_011_a211',)
('a3',)
('gait_011_a300',)
('a3',)
('gait_011_a320',)

In [ ]:
data = np.load('mydataset/gait_753/20250617_c1_a2_Take1/split_subjects/0/keypoints_3d/smpl-keypoints-3d.npy')
print(data.shape)
data= np.load('mydataset/gait_753/20250617_c1_a1_Take1/split_subjects/0/fit-smplx/smpl-keypoints-3d_cut.npy')

print("Keys inside:", data.files)
for k in data.files:
    print(k, data[k].shape)

(53, 25, 5)

AttributeError: 'numpy.ndarray' object has no attribute 'files'

In [ ]:
data= np.load('mydataset/gait_700/20250820_c1_a1_Take1/split_subjects/0/fit-smplx/smplx-params.npz')

print("Keys inside:", data.files)
for k in data.files:
    print(k, data[k].shape)

Keys inside: ['betas', 'global_orient', 'body_pose', 'transl', 'left_hand_pose', 'right_hand_pose', 'jaw_pose', 'leye_pose', 'reye_pose', 'expression']
betas (121, 10)
global_orient (121, 3)
body_pose (121, 63)
transl (121, 3)
left_hand_pose (121, 12)
right_hand_pose (121, 12)
jaw_pose (121, 3)
leye_pose (121, 3)
reye_pose (121, 3)
expression (121, 10)

In [ ]:
from utils.transformation_sixd import smplx_to_6d, sixd_to_smplx

In [ ]:
x=smplx_to_6d("mydataset/gait_011/20251107_c1_a1_Take1/split_subjects/0/fit-smplx/smplx-params_cut.npz")

In [ ]:
x.keys()

dict_keys(['motion_6d', 'transl', 'betas'])

In [ ]:
y=sixd_to_smplx(x)

Performing forward kinematics to calculate joint positions...
Using kid template for SMPL-X model forward kinematics.
Extracting joints for 63 frames...

In [ ]:
np.save('test.npy', y)

In [ ]:
import numpy as np

def generate_keypoints_only_mask(keypoints_path, height_thresh=0.03, vel_thresh=0.05, video_fps=30):
    """
    Determines foot contact purely from kinematics (Keypoints), ignoring the Force Plate.
    
    Criteria for Contact:
    1. Height: Joint Y-coordinate is close to the ground floor.
    2. Velocity: Joint is not moving significantly (Stance phase is static).

    Args:
        keypoints_path (str): Path to .npy keypoints (frames, 25, 3).
        height_thresh (float): Max distance from floor (e.g., 0.03m).
        vel_thresh (float): Max velocity to be considered "static" (e.g., 0.05 m/frame).
        video_fps (int): Video frame rate.

    Returns:
        np.ndarray: Binary mask of shape (frames, 25).
    """
    
    # 1. Load Data
    try:
        keypoints = np.load(keypoints_path) # Shape (F, 25, 3)
        n_frames = keypoints.shape[0]
    except Exception as e:
        print(f"Error: {e}")
        return None

    # 2. Calculate the Floor (Ground Truth)
    # We assume the lowest 5% of ALL foot points in the entire file represent the floor.
    # This is robust to outliers.
    foot_indices = [19, 20, 21, 22, 23, 24] # L/R BigToe, SmallToe, Heel
    all_foot_y = keypoints[:, foot_indices, 1]
    
    # Filter out zeros (undetected points)
    valid_y = all_foot_y[all_foot_y != 0]
    if len(valid_y) == 0:
        print("No valid foot keypoints found.")
        return np.zeros((n_frames, 25), dtype=int)
        
    floor_level = np.percentile(valid_y, 5) # 5th percentile is the estimated floor
    print(f"Auto-detected Floor Level: {floor_level:.4f}")

    velocity = np.linalg.norm(np.diff(keypoints, axis=0, prepend=keypoints[0:1]), axis=2)
    
    is_low = keypoints[:, :, 1] < (floor_level + height_thresh)

    is_static = velocity < vel_thresh
    
    is_detected = keypoints[:, :, 1] != 0

    contact_mask = is_low & is_static & is_detected

    final_mask = np.zeros_like(contact_mask, dtype=int)
    final_mask[:, foot_indices] = contact_mask[:, foot_indices].astype(int)

    return final_mask

In [ ]:
path="mydataset/740/20251002_c1_a3_Take2/split_subjects/0/keypoints_3d/smpl-keypoints-3d.npy"
mask = generate_keypoints_only_mask(path, height_thresh=0.03, vel_thresh=0.04)
data=np.load(path)
masked_data = data * mask[:, :, np.newaxis]
np.save('masked_keypoints.npy', masked_data)
print('saved')

Auto-detected Floor Level: 0.3254
saved

In [ ]:
import os
import numpy as np

for config in os.listdir("results/new"):
    if not config.startswith("config"):
        continue
    config_path=os.path.join("results/new", config)
    for model in os.listdir(config_path):
        data=np.load(os.path.join(config_path, model, "dtw_metrics.npy"), allow_pickle=True)
        print(data)
        break

[{'sample_id': 0, 'dtw_distance': 172.32413447828506, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 187.42159815581, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 234.44739568105066, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 545.4755389302669, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 332.158031307944, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 200.84824775233537, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 374.96440842874046, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 301.52375697000866, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 517.766573394214, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 103.36017961482756, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 191.40730794960888, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 70.90764631736889, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 55.835481497143974, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 286.83543418291583, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 205.04831229220557, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 278.43688504056854, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 230.67735944318198, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 494.11519009136856, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 30.618902068160743, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 317.44703263539475, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 42.85422313855163, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 49.866321935788285, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 209.79588657840364, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 188.56048285646312, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 259.51452974773485, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 250.1677349409184, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 452.49074825772306, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 40.33404489930174, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 209.622613174691, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 35.38079257611008, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 138.67872855850368, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 157.04423178326553, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 167.25403484967595, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 174.1272873744429, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 220.11931145173622, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 717.1158675079516, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 21.58279790594626, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 127.67970973673933, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 42.81389990329609, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 33.666740458835285, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 254.90283913438802, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 159.66121577251377, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 184.64067707277067, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 273.7261789895093, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 517.1652444637124, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 37.03641150157007, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 225.5820281874721, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 36.5986378285834, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 43.38709658350202, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 251.41226156241353, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 161.2497379469188, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 232.89342413803075, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 244.92121820639457, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 609.3663057634732, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 39.13732761522822, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 96.3997267303295, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 54.84554780186093, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 46.56954767692584, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 275.3842733675866, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 144.33536619245297, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 355.7804691137071, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 197.43546916724392, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 511.2505393136068, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 74.15492374313169, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 134.51087524411278, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 56.91636137829737, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 85.03274825909301, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 251.13318381218852, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 160.3078496816939, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 211.9710139730218, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 180.62339730073137, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 480.91403994898116, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 50.875570601792816, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 140.15048866305204, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 44.61575771361362, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 61.22666502654541, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 217.95474155594775, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 111.39281477273609, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 335.21950612745877, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 205.49082495584372, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 452.96162513060165, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 146.32162263701633, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 198.66857412513318, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 147.43320354435846, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 162.80646652168002, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 266.57026006141285, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 319.9913836811999, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 313.65483332442176, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 323.49299471494294, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 467.1855576732524, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 167.41670933292835, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 187.38152595669612, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 228.81936946818152, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 178.43879171292315, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 333.98773367383814, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 269.3380620286388, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 417.80882841995015, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 419.0676156022847, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 645.9035014147377, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 167.75209492570627, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 185.54292648369216, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 155.07801897758984, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 151.12074407936439, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 258.07599737962033, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 316.8191922712725, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 298.4609388214427, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 316.92417444513814, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 489.0446092945424, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 153.88382865059657, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 157.70083444376112, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 221.34737553999756, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 203.19868943144135, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 325.39265671357236, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 340.8775846892364, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 419.10134090303916, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 431.71362747440867, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 655.1306652055027, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 20.232309370699674, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 144.04477245636755, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 27.89675995191421, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 40.75828093237994, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 265.7832678388984, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 152.67353441315208, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 181.02533519438845, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 275.1459353843767, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 506.1053226858337, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 34.57093607719309, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 168.735575949916, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 12.98560201464511, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 32.09361738543788, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 212.44106261755823, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 165.707822316606, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 318.39250222473333, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 297.61422895606785, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 604.8974835800859, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 146.55785670209858, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 209.93516796396202, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 148.88870173279633, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 146.45475610295807, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 268.61922083154764, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 331.6062860168789, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 281.98496699647706, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 339.1586731580153, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 475.04712249540256, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 22.70958031386364, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 143.6575120341175, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 20.4378506150668, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 21.02067528691951, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 221.60573335694036, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 156.1997935818373, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 195.0485143851286, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 257.2411691519618, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 585.6864416900643, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 169.20852329696672, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 174.57901527144958, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 175.98400084328148, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 185.49974542000996, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 303.41731046347286, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 257.2837180108307, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 344.9603972149307, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 352.4606747322957, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 581.3508205935218, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 323.2405786749731, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 265.26964980610404, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 300.38089259875255, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 346.57998192569477, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 569.3153531713881, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 458.1203675570998, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 765.7788106710252, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 732.4699444574298, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 496.50335788438275, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 340.82423397489725, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 485.6123399716876, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 370.8482802541917, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 420.0498253094455, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 299.6252617054457, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 267.5946166321151, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 324.7464199167389, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 338.484798343121, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 572.1213885325188, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 356.11913647218, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 515.6191661850353, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 290.3736583005785, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 573.2982925686977, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 438.2159556651496, 'reference_frames': 82, 'generated_frames': 240}
 {'sample_id': 5, 'dtw_distance': 297.8181636676976, 'reference_frames': 69, 'generated_frames': 240}
 {'sample_id': 6, 'dtw_distance': 472.44066700287834, 'reference_frames': 63, 'generated_frames': 240}
 {'sample_id': 7, 'dtw_distance': 492.835166560145, 'reference_frames': 119, 'generated_frames': 240}
 {'sample_id': 8, 'dtw_distance': 640.2939669011436, 'reference_frames': 268, 'generated_frames': 240}]
[{'sample_id': 0, 'dtw_distance': 37.03641150157007, 'reference_frames': 132, 'generated_frames': 240}
 {'sample_id': 1, 'dtw_distance': 225.5820281874721, 'reference_frames': 165, 'generated_frames': 240}
 {'sample_id': 2, 'dtw_distance': 36.5986378285834, 'reference_frames': 59, 'generated_frames': 240}
 {'sample_id': 3, 'dtw_distance': 43.38709658350202, 'reference_frames': 232, 'generated_frames': 240}
 {'sample_id': 4, 'dtw_distance': 251.41226156241353, 'reference_frames': 82, 'generated_frames': 240}